name: Get modified tabs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: modified_data
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files

        uses: tj-actions/changed-files@v19


      - name: Show all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do

            echo "$file was changed" >> mod_files.log 2>&1

            echo "Count Tab in files: `awk '{print gsub(/\t/,"")}' $file | awk '{s+=$1} END { print s }'`" >> mod_files.log 2>&1
          done
      - name: Report
        uses: actions/upload-artifact@v2
        with:
          path: mod_files.log
