name: Get modified tabs

on: [pull_request]

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    name: modified-data
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Show all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$Files was changed" >> mod_files.log 2>&1
            echo "Count Tab in files: `grep -P '\t' $file | wc -l`" >> mod_files.log 2>&1
          done
      - name: Report
        uses: actions/upload-artifact@v2
        with:
          path: mod_files.log
